spring.application.name=SpringAIwithMCPServer

server.port=8085

spring.ai.mcp.server.protocol=STREAMABLE

# Here mcp is need to hit the MCP server at the end of url. Port number can change
# http://localhost:8085/mcp 