spring.application.name=SpringAIwithVectorDB

server.port=8085

spring.ai.ollama.chat.model=gemma:2b
spring.ai.ollama.embedding.options.model=mxbai-embed-large

# To use online Vector DB -> Pinecone DB use this type API call
#spring.ai.vectorstore.pinecone.api-key=pcsk_2rReob_nTexXesSW4dQQBfduSpzyTm9oGQ6aWsBvkAdg8sVuYGVMd8hq4eVgDrcfxbrVW
#spring.ai.vectorstore.pinecone.index-name=my-spring-ai-vector-db

# In this project I will use my own local docker image Qdrant Vector DB.
# To get Qdrant in cmd type: docker pull qdrant/qdrant
# So before run the project check the docker and DB is up and running
# To check the dashboard of Qdrant DB use : http://localhost:6333/dashboard
spring.ai.vectorstore.qdrant.host=localhost
spring.ai.vectorstore.qdrant.port=6334
spring.ai.vectorstore.qdrant.collection-name=myJobDetails