spring.application.name=SpringAIwithOllama

server.port=8085

spring.ai.ollama.chat.options.model=gemma:2b

spring.ai.ollama.chat.options.max-tokens=10
spring.ai.ollama.chat.options.temperature=1.0

# This project is communicating with gemma:2b model with the help of Ollama tool.
# Best approach is llama3.2 because it support chat model as well as embedded model
# To execute this program we need Ollama tool installed in local instance and I used gemma:2b model form google.
# We can also use other model like gemma:3b, llama3.2 (from META), mistral etc.

# Command to install Ollama and adding any model in local system:
# 1. Download and install Ollama in local system from https://ollama.com/download/windows
# 2. To test Ollama status after install http://localhost:11434
# 3. To test models available or not in local system 
# 		Open CMD type: ollama list
#			It will display the list of model if installed in local system
# 4. To install model in local system
#		Open CMD type: ollama install model_name
#		Ex:	ollama install gemma:2b / ollama install mistral
# 5. To run installed model
#		Open CMD type: ollama run model_name
#		Ex: ollama run gemma:2b
# 6. To exit from opened model
#		In CMD type: bye
# 7. To remove model from local system 
#		Open CMD type: ollama rm model_name
#		Ex: ollama rm mistral