spring.application.name=SpringAIwithOpenAI

spring.ai.openai.api-key=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

server.port=8085