spring.application.name=SpringAIwithMCPClient

server.port=8087

spring.ai.ollama.chat.options.model=llama3.2

# This is a custom url so avoid the syntex error
spring.ai.mcp.client.streamable-http.connections.myMCPServerOne.url=http://localhost:8085/mcp

#For MCP client concept use llama3.2(best) or mistral instead of gemma:2b