spring.application.name=SpringAIEmbeddingText

server.port=8085

spring.ai.ollama.chat.options.model=gemma:2b
spring.ai.ollama.embedding.options.model=mxbai-embed-large
#spring.ai.ollama.chat.options.model=mistral


# To use EmbeddingModel we need this mxbai-embed-large model or llama3.2(Multi model chat + embedding) with Ollama. For OpenAI NOT required.
# To pull EmbeddingModel in local system type in cmd: ollama pull mxbai-embed-large