spring.application.name=SpringAIwithOpenAI

spring.ai.openai.api-key=sk-proj-yBqLGCqTYBKYFyGPcWD32BSyVZdine2-62vQbXihsAvG-2MgZGWI5ZqXlT3BpZ3_AfFZfHwx4PXJJaFTPdYSCwwG7mJUeNLCfaj35ubrP7ImvcV_wAGKUokfySUgTpMA

server.port=8085